-- Migration: Reconciliation engine result tables
-- Adds potential_matches table and engine metadata columns to reconciliation_runs

-- ── potential_matches ──────────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS potential_matches (
    id                      UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    run_id                  UUID NOT NULL REFERENCES reconciliation_runs(id) ON DELETE CASCADE,
    client_id               UUID NOT NULL REFERENCES clients(id) ON DELETE CASCADE,

    pr_row_hash             TEXT NOT NULL,
    gstr2b_row_hash         TEXT NOT NULL,
    gstin_supplier          TEXT NOT NULL,
    pr_invoice_number       TEXT NOT NULL,
    gstr2b_invoice_number   TEXT NOT NULL,

    similarity_score        NUMERIC(6, 4) NOT NULL CHECK (similarity_score BETWEEN 0 AND 1),
    confidence              TEXT NOT NULL CHECK (confidence IN ('exact', 'high', 'medium', 'low')),
    field_variances         JSONB DEFAULT '[]',
    suggested_action        TEXT,

    review_status           TEXT NOT NULL DEFAULT 'pending'
                                CHECK (review_status IN ('pending', 'accepted', 'rejected', 'escalated')),
    reviewed_by             UUID REFERENCES users(id),
    reviewed_at             TIMESTAMP WITH TIME ZONE,
    review_note             TEXT,

    detected_at             TIMESTAMP WITH TIME ZONE DEFAULT NOW(),

    CONSTRAINT potential_matches_pair_unique
        UNIQUE (run_id, pr_row_hash, gstr2b_row_hash)
);

-- ── matched_records enhancements ──────────────────────────────────────────────
-- Add confidence + field variance columns if not already present
ALTER TABLE matched_records
    ADD COLUMN IF NOT EXISTS confidence        TEXT DEFAULT 'high',
    ADD COLUMN IF NOT EXISTS pr_taxable_value  NUMERIC(15, 2) DEFAULT 0,
    ADD COLUMN IF NOT EXISTS gstr2b_taxable_value NUMERIC(15, 2) DEFAULT 0,
    ADD COLUMN IF NOT EXISTS pr_igst           NUMERIC(15, 2) DEFAULT 0,
    ADD COLUMN IF NOT EXISTS gstr2b_igst       NUMERIC(15, 2) DEFAULT 0,
    ADD COLUMN IF NOT EXISTS pr_cgst           NUMERIC(15, 2) DEFAULT 0,
    ADD COLUMN IF NOT EXISTS gstr2b_cgst       NUMERIC(15, 2) DEFAULT 0,
    ADD COLUMN IF NOT EXISTS pr_sgst           NUMERIC(15, 2) DEFAULT 0,
    ADD COLUMN IF NOT EXISTS gstr2b_sgst       NUMERIC(15, 2) DEFAULT 0,
    ADD COLUMN IF NOT EXISTS value_variance    NUMERIC(15, 2) DEFAULT 0,
    ADD COLUMN IF NOT EXISTS tax_variance      NUMERIC(15, 2) DEFAULT 0,
    ADD COLUMN IF NOT EXISTS field_variances   JSONB DEFAULT '[]',
    ADD COLUMN IF NOT EXISTS matched_on        JSONB DEFAULT '["gstin_supplier","invoice_number"]';

-- ── unmatched_records enhancements ───────────────────────────────────────────
ALTER TABLE unmatched_records
    ADD COLUMN IF NOT EXISTS total_tax     NUMERIC(15, 2) DEFAULT 0,
    ADD COLUMN IF NOT EXISTS cess          NUMERIC(15, 2) DEFAULT 0,
    ADD COLUMN IF NOT EXISTS itc_impact    NUMERIC(15, 2) DEFAULT 0;

-- ── reconciliation_runs: engine tracking ──────────────────────────────────────
ALTER TABLE reconciliation_runs
    ADD COLUMN IF NOT EXISTS engine_name       TEXT,
    ADD COLUMN IF NOT EXISTS run_metrics       JSONB DEFAULT '{}';

-- ── Indexes ────────────────────────────────────────────────────────────────────
CREATE INDEX IF NOT EXISTS idx_potential_matches_run_id
    ON potential_matches (run_id, client_id);

CREATE INDEX IF NOT EXISTS idx_potential_matches_gstin
    ON potential_matches (client_id, gstin_supplier);

CREATE INDEX IF NOT EXISTS idx_potential_matches_review_status
    ON potential_matches (run_id, review_status);

CREATE INDEX IF NOT EXISTS idx_matched_records_confidence
    ON matched_records (run_id, confidence);

-- ── RLS policies for potential_matches ───────────────────────────────────────
ALTER TABLE potential_matches ENABLE ROW LEVEL SECURITY;

CREATE POLICY potential_matches_tenant_isolation ON potential_matches
    USING (client_id::text = current_setting('app.current_tenant', true));

-- ── Comments ──────────────────────────────────────────────────────────────────
COMMENT ON TABLE potential_matches IS
    'Invoice pairs that partially match — require auditor review before acceptance';

COMMENT ON COLUMN potential_matches.similarity_score IS
    'RapidFuzz token_sort_ratio / 100 for the invoice number pair';

COMMENT ON COLUMN potential_matches.suggested_action IS
    'Human-readable recommendation generated by the reconciliation engine';

COMMENT ON COLUMN reconciliation_runs.engine_name IS
    'Which reconciliation engine processed this run (reconlify_cli | pandas_fallback)';

COMMENT ON COLUMN reconciliation_runs.run_metrics IS
    'JSON snapshot of ReconMetrics at the time of completion';
